[package]
name = "qcli-driver-api"
description = "Engine adapter contract for qcli"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
arrow-array.workspace = true
async-trait.workspace = true
tokio.workspace = true

[lints]
workspace = true
