[package]
name = "qcli-driver-trino"
description = "Trino HTTP protocol adapter for qcli"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
arrow-array.workspace = true
arrow-json.workspace = true
arrow-schema.workspace = true
async-trait.workspace = true
qcli-driver-api = { path = "../qcli-driver-api" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
trino-rust-client.workspace = true
url.workspace = true

[lints]
workspace = true
