[package]
name = "qcli-core"
description = "Session and query orchestration for qcli"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
arrow-array.workspace = true
qcli-config = { path = "../qcli-config" }
qcli-driver-api = { path = "../qcli-driver-api" }
tokio.workspace = true

[dev-dependencies]
qcli-driver-demo = { path = "../qcli-driver-demo" }

[lints]
workspace = true
