[package]
name = "qcli-repl"
description = "Interactive terminal frontend for qcli"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
qcli-config = { path = "../qcli-config" }
qcli-core = { path = "../qcli-core" }
qcli-driver-api = { path = "../qcli-driver-api" }
qcli-output = { path = "../qcli-output" }
rustyline.workspace = true
signal-hook.workspace = true
tokio.workspace = true

[lints]
workspace = true
