[package]
name = "qcli"
description = "One query shell for cloud data platforms"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
qcli-config = { path = "../qcli-config" }
qcli-core = { path = "../qcli-core" }
qcli-driver-api = { path = "../qcli-driver-api" }
qcli-driver-demo = { path = "../qcli-driver-demo" }
qcli-driver-trino = { path = "../qcli-driver-trino" }
qcli-output = { path = "../qcli-output" }
tokio.workspace = true

[lints]
workspace = true
